//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Cabinet_Medical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs_Diseases
    {
        public int ID_Afectiune { get; set; }
        public int ID_Medicament { get; set; }
        public int ID { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Drug Drug { get; set; }
    }
}
