//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Cabinet_Medical
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistView
    {
        public string Nume { get; set; }
        public string Specializare { get; set; }
        public string Denumire { get; set; }
        public System.DateTime Data { get; set; }
        public int ID { get; set; }
    }
}
