//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Cabinet_Medical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int ID_Istoric { get; set; }
        public int ID_Medicament { get; set; }
        public int Numar_Flacoane { get; set; }
        public int ID { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual History_Patients History_Patients { get; set; }
    }
}
